// examples/vue3/src/components/ColorButton.vue
<script lang="ts" setup>
defineProps({
    bgcolorselect: {
        type: String,
        default: null,
    },
    txtcolorselect: {
        type: String,
        default: null,
    },
})
</script>

<template>
    <button :style="{ background: bgcolorselect, color: txtcolorselect }" class="htw-px-2 htw-py-1 htw-rounded-sm btn">
        <slot />
    </button>
</template>

<style scoped>
.btn {
    cursor: pointer;
}
</style>

// examples/svelte4/src/ColorButton.svelte
<script lang="ts">
    export let disabled: boolean = false
    export let colorselect = "#d5bebe"
  </script>
  
  <button class:disabled class={"button"} style="background: {colorselect}" on:click>
    <slot />
  </button>
  
  <style>
  button {
    color: white;
    border-radius: 6px;
    cursor: pointer;
    transition: opacity .15s;
    padding: 7px 16px;
    font-size: 24px;
  }
  
  button.disabled {
    opacity: 0.5;
  }
  </style>
