// examples/nuxt3-i18n/components/BaseButton.vue
<script lang="ts" setup>
defineProps({
  color: {
    type: String,
    default: null,
  },

  size: {
    type: String,
    default: null,
  },

  disabled: {
    type: Boolean,
    default: false,
  },
})
</script>

<template>
  <button
    :disabled="disabled"
    class="btn text-red-500"
    :class="{
      [`btn-color-${color}`]: color,
      [`btn-size-${size}`]: size,
    }"
    data-testid="base-button"
  >
    <slot />
  </button>
</template>

<style lang="pcss" scoped>
.btn {
  border-radius: 4px;
  padding: 4px 8px;
  background: #e4e4e4;
  cursor: pointer;
}

.btn:hover {
  background: #f1f1f1;
}

.btn[disabled] {
  opacity: 0.5;
  pointer-events: none;
}

.btn-color-green {
  background: #94ffc9;
}

.btn-color-green:hover {
  background: #acffd6;
}

.btn-color-red {
  background: #ff9494;
}

.btn-color-red:hover {
  background: #ffa8a8;
}

.btn-size-big {
  font-size: 16px;
  padding: 8px 16px;
}

.btn-size-small {
  font-size: 12px;
  padding: 2px 4px;
}
</style>

// examples/svelte3/src/BaseButton.svelte
<script lang="ts">
  export let disabled: boolean = false
  export let size: 'small' | 'medium' | 'large' = 'medium'
</script>

<button class:disabled class={size} on:click>
  <slot />
</button>

<style>
button {
  background: #ff3e00;
  color: white;
  border-radius: 6px;
  cursor: pointer;
}

button.small {
  padding: 6px;
}

button.medium {
  padding: 12px;
}

button.large {
  padding: 24px;
}

button.disabled {
  opacity: 0.5;
}
</style>
