// packages/histoire-plugin-vue/src/client/server/Story.vue
<script lang="ts">
import { defineComponent, inject, onMounted, PropType, provide, useAttrs } from 'vue'
import type { ServerStoryFile, ServerStory, ServerVariant } from '@histoire/shared'

const stub = { name: 'StubbedComponent', render: () => null }

export default defineComponent({
  name: 'HistoireStory',

  inheritAttrs: false,

  props: {
    title: {
      type: String,
      default: null,
    },

    id: {
      type: String,
      default: null,
    },

    group: {
      type: String,
      default: null,
    },

    layout: {
      type: Object as PropType<ServerStory['layout']>,
      default: () => ({ type: 'single', iframe: true }),
    },

    icon: {
      type: String,
      default: null,
    },

    iconColor: {
      type: String,
      default: null,
    },

    docsOnly: {
      type: Boolean,
      default: false,
    },
  },

  setup (props) {
    const attrs = useAttrs() as {
      data: ServerStoryFile
    }

    // Story

    const story: ServerStory = {
      id: props.id ?? attrs.data.id,
      title: props.title ?? attrs.data.fileName,
      group: props.group,
      layout: props.layout,
      icon: props.icon,
      iconColor: props.iconColor,
      docsOnly: props.docsOnly,
      variants: [],
    }
    const addStory = inject('addStory', null)
    addStory?.(story)

    // Variants

    provide('story', story)

    provide('addVariant', (variant: ServerVariant) => {
      story.variants.push(variant)
    })

    onMounted(() => {
      if (!story.variants.length) {
        story.variants.push({
          id: '_default',
          title: 'default',
        })
      }
    })

    return {
      story,
    }
  },

  render () {
    let suppressError = false
    try {
      const vnodes = this.$slots.default?.({
        get state () {
          // No variant tags
          suppressError = true
          return {}
        },
      })

      // Auto stub components
      if (Array.isArray(vnodes)) {
        for (const vnode of vnodes) {
          if (typeof vnode.type === 'object' && (vnode.type as any).name !== 'HistoireVariant') {
            vnode.type = stub
          }
        }
      }

      return vnodes
    } catch (e) {
      if (!suppressError) {
        console.error(e)
      }
      return null
    }
  },
})
</script>

// packages/histoire-plugin-svelte/src/collect/Story.svelte
<script lang="ts">
import { ServerStory, ServerStoryFile, ServerVariant } from '@histoire/shared'
import { getContext, setContext } from 'svelte'

export let title: string = null
export let id: string = null
export let group: string = null
export let layout: ServerStory['layout'] = { type: 'single', iframe: true }
export let icon: string = null
export let iconColor: string = null
export let docsOnly: boolean = false

const addStory: (story: ServerStory) => void = getContext('__hstAddStory')
const file: ServerStoryFile = getContext('__hstStoryFile')

const story: ServerStory = {
  id: id ?? file.id,
  title: title ?? file.fileName,
  group,
  layout,
  icon,
  iconColor,
  docsOnly,
  variants: [],
}

addStory(story)

setContext('__hstStory', story)
setContext('__hstAddVariant', (variant: ServerVariant) => {
  story.variants.push(variant)
})
</script>

<slot />
