// packages/histoire-plugin-svelte/src/collect/Variant.svelte
<script>
import { getContext } from 'svelte'

export let title = 'untitled'
export let id = null
export let icon = null
export let iconColor = null

const story = getContext('__hstStory')
const addVariant = getContext('__hstAddVariant')

function generateId () {
  return `${story.id}-${story.variants.length}`
}

const variant = {
  id: id ?? generateId(),
  title,
  icon,
  iconColor,
}

addVariant(variant)
</script>

// packages/histoire/src/client/server/vue3/Variant.vue
<script lang="ts">
import { defineComponent, inject } from 'vue'
import type { Story, Variant } from '../../node/types'

export default defineComponent({
  props: {
    title: {
      type: String,
      default: 'untitled',
    },

    id: {
      type: String,
      default: null,
    },

    icon: {
      type: String,
      default: null,
    },

    iconColor: {
      type: String,
      default: null,
    },
  },

  setup (props) {
    const story = inject<Story>('story')

    function generateId () {
      return `${story.id}-${story.variants.length}`
    }

    const variant: Variant = {
      id: props.id ?? generateId(),
      title: props.title,
      icon: props.icon,
      iconColor: props.iconColor,
    }

    const addVariant = inject('addVariant') as (variant: Variant) => void
    addVariant(variant)
  },

  render () {
    return null
  },
})
</script>
