// packages/histoire-plugin-svelte/src/collect/Variant.svelte
<script lang="ts">
import { ServerStory, ServerVariant } from '@histoire/shared'
import { getContext } from 'svelte'

export let title: string = 'untitled'
export let id: string = null
export let icon: string = null
export let iconColor: string = null

const story: ServerStory = getContext('__hstStory')
const addVariant: (variant: ServerVariant) => void = getContext('__hstAddVariant')

function generateId () {
  return `${story.id}-${story.variants.length}`
}

const variant: ServerVariant = {
  id: id ?? generateId(),
  title,
  icon,
  iconColor,
}

addVariant(variant)
</script>

// packages/histoire-plugin-vue/src/client/server/Variant.vue
<script lang="ts">
import { defineComponent, inject } from 'vue'
import type { ServerStory, ServerVariant } from '@histoire/shared'

export default defineComponent({
  name: 'HistoireVariant',

  props: {
    title: {
      type: String,
      default: 'untitled',
    },

    id: {
      type: String,
      default: null,
    },

    icon: {
      type: String,
      default: null,
    },

    iconColor: {
      type: String,
      default: null,
    },
  },

  setup (props) {
    const story = inject<ServerStory>('story')

    function generateId () {
      return `${story.id}-${story.variants.length}`
    }

    const variant: ServerVariant = {
      id: props.id ?? generateId(),
      title: props.title,
      icon: props.icon,
      iconColor: props.iconColor,
    }

    const addVariant = inject('addVariant') as (variant: ServerVariant) => void
    addVariant(variant)
  },

  render () {
    return null
  },
})
</script>
